=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/Checkbox/json/paramsSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "itemType": "iic",
  "type": "object",
  "id": "Checkbox",
  "properties": {
    "version": {
      "id": "version",
      "type": "string",
      "title": "version",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "itemName": {
      "id": "itemName",
      "type": "string",
      "title": "itemName",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "itemType": {
      "id": "itemType",
      "type": "string",
      "title": "itemType",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "paramIdScore0001": {
      "id": "paramIdScore0001",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramIdScore0001",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0001": {
      "id": "paramId0001",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0001",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0002": {
      "id": "paramId0002",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0002",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0003": {
      "id": "paramId0003",
      "type": "object",
      "title": "paramId0003",
      "properties": {
        "content": {
          "type": "array",
          "title": "paramId0003",
          "maxItems": 10,
          "id": "paramId0003-content",
          "items": {
            "type": "object",
            "properties": {
              "label": {
                "id": "label",
                "type": "string",
                "title": "Label",
                "mediaType": "text",
                "hidden": false,
                "disabled": false
              },
              "value": {
                "id": "value",
                "type": "string",
                "title": "Value",
                "mediaType": "text",
                "hidden": false,
                "disabled": false
              },
              "selected": {
                "id": "selected",
                "type": "string",
                "title": "Selected",
                "mediaType": "option-select",
                "hidden": false,
                "disabled": false,
                "optional": false,
                "enum": ["true", "false"]
              }
            }
          }
        }
      }
    }
  }
}

=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/RadioGroup/json/params.json
{
  "version": "1.0",
  "itemName": "RadioGroup",
  "itemType": "iic",
  "paramIdScore0001": {
    "content": "",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0001": {
    "content": "RadioGroup",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0002": {
    "content": "RadioResponse",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0003": {
    "content": [
      {
        "label": "option 1",
        "value": "1",
        "optionLabel": null,
        "selected": "false"
      },
      {
        "label": "option 2",
        "value": "2",
        "optionLabel": null,
        "selected": "false"
      },
      {
        "label": "option 3",
        "value": "3",
        "optionLabel": null,
        "selected": "false"
      },
      {
        "label": "option 4",
        "value": "4",
        "optionLabel": null,
        "selected": "false"
      },
      {
        "label": "option 5",
        "value": "5",
        "optionLabel": null,
        "selected": "false"
      }
    ],
    "ref": "",
    "scene": "scene1"
  }
}

=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/Checkbox/json/params.json
{
  "version": "1.0",
  "itemName": "Checkbox",
  "itemType": "iic",
  "paramIdScore0001": {
    "content": "",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0001": {
    "content": "checkboxResponse",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0002": {
    "content": "checkbox",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0003": {
    "content": [
      {
        "label": "option 1",
        "value": "option 1",
        "optionLabel": null,
        "selected": "false"
      },
      {
        "label": "option 2",
        "value": "option 2",
        "optionLabel": null,
        "selected": "false"
      },
      {
        "label": "option 3",
        "value": "option 3",
        "optionLabel": null,
        "selected": "false"
      },
      {
        "label": "option 4",
        "value": "option 4",
        "optionLabel": null,
        "selected": "false"
      },
      {
        "label": "option 5",
        "value": "option 5",
        "optionLabel": null,
        "selected": "false"
      }
    ],
    "ref": "",
    "scene": "scene1"
  }
}

=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/EliminateList/json/params.json
{
  "version": "1.0",
  "itemName": "Eliminate List",
  "itemType": "iic",
  "paramId0001": {
    "content": "eliminateListResponse",
    "ref": "",
    "scene": "scene1"
  },
  "paramIdScore0001": {
    "content": "",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0002": {
    "content": "eliminatelist",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0003": {
    "content": [
      {
        "label": "option 1",
        "value": "option 1",
        "selected": "false"
      },
      {
        "label": "An option with a longer label",
        "value": "option 2",
        "selected": "false"
      },
      {
        "label": "option 3",
        "value": "option 3",
        "selected": "false"
      },
      {
        "label": "option 4",
        "value": "option 4",
        "selected": "false"
      },
      {
        "label": "option 5",
        "value": "option 5",
        "selected": "false"
      }
    ],
    "ref": "",
    "scene": "scene1"
  }
}
