=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/Button/json/paramsSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "itemType": "iic",
  "type": "object",
  "id": "Button",
  "properties": {
    "version": {
      "id": "version",
      "type": "string",
      "title": "version",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "itemName": {
      "id": "itemName",
      "type": "string",
      "title": "itemName",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "itemType": {
      "id": "itemType",
      "type": "string",
      "title": "itemType",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "paramId0001": {
      "id": "paramId0001",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0001",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0002": {
      "id": "paramId0002",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0002",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0003": {
      "id": "paramId0003",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0003",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0010": {
      "id": "paramId0010",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0010",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    }
  }
}

=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/Button/json/params.json
{
  "version": "1.0",
  "itemName": "Button",
  "itemType": "iic",
  "paramId0001": {
    "content": "ButtonResponse",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0002": {
    "content": "Button",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0003": {
    "content": "Button",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0010": {
    "content": "",
    "ref": "",
    "scene": "scene1"
  }
}
