=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/Image/json/paramsSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "itemType": "iic",
  "type": "object",
  "id": "Image",
  "properties": {
    "version": {
      "id": "version",
      "type": "string",
      "title": "version",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "itemName": {
      "id": "itemName",
      "type": "string",
      "title": "itemName",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "itemType": {
      "id": "itemType",
      "type": "string",
      "title": "itemType",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "paramIdScore0001": {
      "id": "paramIdScore0001",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "scoreId0001",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0001": {
      "id": "paramId0001",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0001",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0002": {
      "id": "paramId0002",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0002",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0003": {
      "id": "paramId0003",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0003",
          "mediaType": "image",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0004": {
      "id": "paramId0004",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0004",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0005": {
      "id": "paramId0005",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0005",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0006": {
      "id": "paramId0006",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0006",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    }
  }
}

=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/Image/json/params.json
{
  "version": "1.0",
  "itemName": "Image",
  "itemType": "iic",
  "paramIdScore0001": {
    "content": "",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0001": {
    "content": "image001",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0002": {
    "content": "Cutebunny",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0003": {
    "content": "one-day-things-will-get-better-until-then-here-is-a-drawing-of-a-cat.jpg",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0004": {
    "content": "Bunny",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0005": {
    "content": "400",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0006": {
    "content": "400",
    "ref": "",
    "scene": "scene1"
  }
}
