=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/Placeholder/json/paramsSchema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "itemType": "iic",
  "type": "object",
  "id": "Placeholder",
  "properties": {
    "version": {
      "id": "version",
      "type": "string",
      "title": "version",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "itemName": {
      "id": "itemName",
      "type": "string",
      "title": "itemName",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "itemType": {
      "id": "itemType",
      "type": "string",
      "title": "itemType",
      "mediaType": "text",
      "hidden": true,
      "disabled": true
    },
    "params0001": {
      "id": "params0001",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "params0001",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0001": {
      "id": "paramId0001",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0001",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0002": {
      "id": "paramId0002",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0002",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0003": {
      "id": "paramId0003",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0003",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    },
    "paramId0004": {
      "id": "paramId0004",
      "type": "object",
      "properties": {
        "content": {
          "type": "string",
          "title": "paramId0004",
          "mediaType": "html",
          "hidden": false,
          "disabled": false
        }
      }
    }
  }
}

=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/Popover/json/params.json
{
  "version": "1.0",
  "itemName": "Popover",
  "itemType": "iic",
  "paramId0001": {
    "content": "PopoverResponse",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0002": {
    "content": "Popover",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0003": {
    "content": "Popover Button",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0004": {
    "content": "Hello There!",
    "ref": "",
    "scene": "scene1"
  }
}

=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/Placeholder/json/params.json
{
  "version": "1.0",
  "itemName": "Placeholder",
  "itemType": "iic",
  "params0001": {
    "content": "<p>Placeholder component:</p><hr><span data-type=\"component\" id=\"placeholder0001\"></span>",
    "ref": ""
  },
  "paramId0001": {
    "content": "placeholder",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0002": {
    "content": "Placeholder",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0003": {
    "content": "100",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0004": {
    "content": "80",
    "ref": "",
    "scene": "scene1"
  }
}

=== PankajGoGuardian/edulastic-poc-clone/public/testlets/testlet-musicmixer/utility/components/Text/json/params.json
{
  "version": "1.0",
  "itemName": "Text",
  "itemType": "iic",
  "params0001": {
    "content": "<p>Text component:</p><p><span data-type=\"component\" id=\"text0001\"></span></p>",
    "ref": ""
  },
  "paramId0001": {
    "content": "TextResponse",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0002": {
    "content": "Text",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0003": {
    "content": "Hi There! I'm the text component!",
    "ref": "",
    "scene": "scene1"
  },
  "paramId0004": {
    "content": "Text-value",
    "ref": "",
    "scene": "scene1"
  }
}
